// Optional development check: NODE_PATH=<jsdom node_modules> node this-file <demo review.html>
// This exercises generated HTML in a DOM emulator. It does not verify browser layout.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM, VirtualConsole } = require('jsdom');
const errors = [];
const console = new VirtualConsole();
console.on('jsdomError', error => errors.push(error.message));
const dom = new JSDOM(fs.readFileSync(process.argv[2], 'utf8'), {
  runScripts: 'dangerously', url: 'https://mandiff.invalid/', virtualConsole: console,
});
const { window } = dom, document = window.document;
const q = selector => { const item = document.querySelector(selector); assert.ok(item, selector); return item; };
const click = selector => q(selector).dispatchEvent(new window.MouseEvent('click', {bubbles: true}));
const stack = () => [...document.querySelectorAll('.cg-stack button')].map(item => item.textContent.replace(/^\d+\. /, ''));
assert.deepEqual(errors, []);
if (!document.querySelector('#context-guide svg')) {
  const details = q('#context-guide > details');
  details.open = true;
  details.dispatchEvent(new window.Event('toggle'));
}
assert.equal(document.querySelectorAll('#context-guide svg').length, 1);
assert.deepEqual(stack(), ['request()']);
click('[data-guide-view="calls"]');
assert.equal(document.querySelectorAll('.cg-diagram [data-cg-node]').length, 6);
click('.cg-diagram [data-cg-node="refresh"]');
assert.match(q('.cg-detail-text').textContent, /写入缓存/);
assert.match(q('.cg-evidence').textContent, /service.py:1/);
assert.match(q('.cg-evidence code').textContent, /def refresh/);
click('.cg-relations [data-cg-edge="0"]');
assert.match(q('.cg-detail-title').textContent, /同步调用 load/);
q('.cg-scenarios').value = '1';
q('.cg-scenarios').dispatchEvent(new window.Event('change', {bubbles: true}));
click('[data-cg-next]');
click('[data-cg-next]');
assert.deepEqual(stack(), ['request()', 'load()', 'schedule()']);
assert.ok(q('.cg-diagram [data-cg-step="enqueue"]').classList.contains('cg-active'));
click('[data-cg-next]');
assert.deepEqual(stack(), ['request()', 'load()']);
click('[data-cg-next]');
assert.deepEqual(stack(), ['request()']);
click('[data-cg-next]');
assert.deepEqual(stack(), ['tick()']);
assert.match(q('.cg-detail-text').textContent, /不在当前栈中/);
assert.equal(q('.cg-counter').textContent, '6 / 10');
click('.cg-diagram [data-cg-step="fetch"]');
assert.equal(q('.cg-counter').textContent, '8 / 10');
assert.deepEqual(stack(), ['tick()', 'refresh()', 'fetch()']);
click('.cg-diagram [data-cg-step="cached"]');
assert.equal(q('.cg-scenarios').value, '0');
assert.equal(q('.cg-counter').textContent, '3 / 3');
assert.deepEqual(stack(), ['request()']);
assert.equal(q('[data-cg-next]').disabled, true);
q('.cg-diagram [data-cg-step="lookup"]').dispatchEvent(new window.KeyboardEvent('keydown', {key: 'Enter', bubbles: true}));
assert.deepEqual(stack(), ['request()', 'load()']);
assert.equal(q('.cg-counter').textContent, '2 / 3');
assert.equal(document.querySelectorAll('script[src], link[rel="stylesheet"]').length, 0);
assert.deepEqual(errors, []);
const renderGuide = window.eval('renderContextGuide');
const model = JSON.parse(q('#mandiff-data').textContent);
const guide = model.units[0].baseline.guide;
// Exercise renderer limits independently of report validation.
const hostile = structuredClone(guide), sources = structuredClone(model.context_sources);
hostile.nodes[0].label = '<img src=x onerror="window.injected=true">';
sources[0].excerpt = '</code><script>window.injected=true</script>';
renderGuide(q('#context-guide'), hostile, sources);
click('.cg-diagram [data-cg-node="app"]');
assert.equal(document.querySelectorAll('#context-guide img, #context-guide script').length, 0);
assert.equal(window.injected, undefined);
assert.match(q('.cg-evidence code').textContent, /<script>/);
assert.deepEqual(stack(), ['request()']);
const cyclic = structuredClone(guide);
cyclic.relations.push({from: 'load', to: 'request', kind: 'calls', label: 'Recursive fixture', context_refs: ['C01']});
renderGuide(q('#context-guide'), cyclic, model.context_sources);
click('[data-guide-view="calls"]');
assert.ok(!/NaN|Infinity/.test(q('.cg-diagram svg').outerHTML));
const declaration = structuredClone(guide);
declaration.execution = {status: 'not_applicable', reason: '只有声明，无执行过程。'};
renderGuide(q('#context-guide'), declaration, model.context_sources);
click('[data-guide-view="flow"]');
assert.match(q('.cg-diagram').textContent, /只有声明/);
assert.equal(document.querySelectorAll('.cg-scenarios, .cg-stack').length, 0);
renderGuide(q('#context-guide'), null, []);
assert.match(q('#context-guide').textContent, /older report/);
assert.equal(document.querySelectorAll('#context-guide svg').length, 0);
assert.deepEqual(errors, []);
dom.window.close();
process.stdout.write('Context guide DOM checks passed: views, source navigation, branches, returns, async stacks, graph-to-scenario selection, keyboard, escaping, cycles, non-executable and legacy reports.\n');
